-- DB2 target DDL. Not executed or DB2-validated in this repository.
-- Direct ledger writes must be denied to all application/agent identities.
-- No posting procedure is shipped: the posting boundary is unavailable.
CREATE TABLE PROVENANCE (
    PROV_ID CHAR(36) NOT NULL PRIMARY KEY,
    SOURCE_ID VARCHAR(64) NOT NULL,
    SOURCE_LOC VARCHAR(128) NOT NULL,
    AGENT_ID CHAR(16) NOT NULL,
    TOOL_ID CHAR(32) NOT NULL,
    TS TIMESTAMP NOT NULL,
    INPUT_HASH CHAR(64) NOT NULL,
    OUTPUT_HASH CHAR(64) NOT NULL,
    TRANSFORM VARCHAR(256) NOT NULL,
    PARENT_PROV CHAR(36),
    RULE_CHAIN VARCHAR(512) NOT NULL,
    ASSUMPTIONS VARCHAR(2048) NOT NULL,
    UNCERTAINTY DECIMAL(4,3) NOT NULL,
    RISK SMALLINT NOT NULL,
    CONSTRAINT CK_UNCERT CHECK (UNCERTAINTY BETWEEN 0 AND 1),
    CONSTRAINT CK_RISK CHECK (RISK BETWEEN 0 AND 9999),
    CONSTRAINT FK_PARENT FOREIGN KEY (PARENT_PROV) REFERENCES PROVENANCE
);
CREATE TABLE LEDGER_ACCOUNT (
    ACCOUNT_ID CHAR(36) NOT NULL PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR(34) NOT NULL UNIQUE,
    CURRENCY CHAR(3) NOT NULL,
    STATUS CHAR(12) NOT NULL,
    CREATED_TS TIMESTAMP NOT NULL,
    PROVENANCE_ID CHAR(36) NOT NULL REFERENCES PROVENANCE
);
CREATE TABLE LEDGER_JOURNAL (
    JOURNAL_ID CHAR(36) NOT NULL PRIMARY KEY,
    REQUEST_ID CHAR(36) NOT NULL UNIQUE,
    CURRENCY CHAR(3) NOT NULL,
    STATUS CHAR(12) NOT NULL,
    PROVENANCE_ID CHAR(36) NOT NULL REFERENCES PROVENANCE,
    CONSTRAINT CK_JSTATUS CHECK (STATUS IN ('DRAFT', 'POSTED', 'REVERSED'))
);
CREATE TABLE LEDGER_ENTRY (
    ENTRY_ID CHAR(36) NOT NULL PRIMARY KEY,
    JOURNAL_ID CHAR(36) NOT NULL REFERENCES LEDGER_JOURNAL,
    ACCOUNT_ID CHAR(36) NOT NULL REFERENCES LEDGER_ACCOUNT,
    DEBIT_AMT DECIMAL(19,4) NOT NULL DEFAULT 0,
    CREDIT_AMT DECIMAL(19,4) NOT NULL DEFAULT 0,
    VALUE_DATE DATE NOT NULL,
    BOOKING_DATE DATE NOT NULL,
    PROVENANCE_ID CHAR(36) NOT NULL REFERENCES PROVENANCE,
    INPUT_HASH CHAR(64) NOT NULL,
    OUTPUT_HASH CHAR(64) NOT NULL,
    CONSTRAINT CK_ENTRY_SIDE CHECK (
        (DEBIT_AMT > 0 AND CREDIT_AMT = 0) OR
        (CREDIT_AMT > 0 AND DEBIT_AMT = 0))
);
CREATE TABLE AUDIT_EVENT (
    EVENT_ID CHAR(36) NOT NULL PRIMARY KEY,
    EVENT_SEQUENCE BIGINT NOT NULL UNIQUE,
    TRACE_ID CHAR(36) NOT NULL,
    REQUEST_ID CHAR(36) NOT NULL,
    GRAPH_ID CHAR(36) NOT NULL,
    AGENT_ID CHAR(16) NOT NULL,
    FUNCTOR_ID CHAR(32) NOT NULL,
    INPUT_HASH CHAR(64) NOT NULL,
    OUTPUT_HASH CHAR(64) NOT NULL,
    PREV_EVENT_HASH CHAR(64) NOT NULL,
    EVENT_HASH CHAR(64) NOT NULL,
    TS TIMESTAMP NOT NULL,
    RESULT CHAR(16) NOT NULL,
    RISK SMALLINT NOT NULL,
    PROV_REF CHAR(36) REFERENCES PROVENANCE
);
-- Diagnostic only. This query does not authorize or enforce posting.
SELECT JOURNAL_ID, SUM(DEBIT_AMT) AS DEBITS, SUM(CREDIT_AMT) AS CREDITS
FROM LEDGER_ENTRY
GROUP BY JOURNAL_ID
HAVING SUM(DEBIT_AMT) <> SUM(CREDIT_AMT);
